#!/bin/sh

#################################
# Set up Ethernet bridge on Linux
# Requires: bridge-utils
#################################

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged,
# for example tap="tap0 tap1 tap2".
tap="tap0"

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth="eth0"

# take the current IP and set it on the bridge
sleep 5
eval $( ifdata -p $eth | awk '{ print "eth_ip=\"" $1 "\"\neth_netmask=\"" $2 "\"\neth_broadcast=\"" $3 "\"" }' )
if [ "$eth_ip" = "NON-IP" ]; then
        exit 1
fi
pkill -f dhclient

for t in $tap; do
    openvpn --mktun --dev $t
done

brctl addbr $br
brctl addif $br $eth

for t in $tap; do
    brctl addif $br $t
done

for t in $tap; do
    ifconfig $t 0.0.0.0 promisc up
done

ifconfig $eth 0.0.0.0 promisc up

ifconfig $br $eth_ip netmask $eth_netmask broadcast $eth_broadcast
